[Eth]
NetworkId = 56
LightPeers = 100
TrieTimeout = 150000000000

[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 1
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["admin", "net", "web3", "eth", "miner", "txpool", "personal"]
WSPort = 8546
WSModules = ["admin", "net", "web3", "eth", "miner", "txpool", "personal"]

[Metrics]
Enabled = true
HTTP = "127.0.0.1"
Port = 6061

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
# for bloxroute gateway
StaticNodes = [
"enode://912e6ce5c4328ec3df679496e4f709b77b546587c45c7dd8d4b5c80c47034bdc533fc0715bbf22e596bbc810837ae2838b5b9ab276beeaac1dbb031ce0d8149e@127.0.0.1:0"
]
TrustedNodes = ["enode://912e6ce5c4328ec3df679496e4f709b77b546587c45c7dd8d4b5c80c47034bdc533fc0715bbf22e596bbc810837ae2838b5b9ab276beeaac1dbb031ce0d8149e"]
ListenAddr = ":30303"
EnableMsgEvents = false
