name: IAC Lint

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  files-changed:
    if: ${{ github.event_name == 'pull_request' }}
    name: Determine Files Changed
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.path-filter.outputs.files }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Path Filter
        id: path-filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            files:
              - .github/workflows/iac.lint.yaml
              - iac/**

  lint:
    needs: files-changed
    if: ${{ needs.files-changed.outputs.files == 'true' }}
    name: IAC Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: 'pip'
          cache-dependency-path: iac/requirements.txt

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install ruff
        working-directory: ./iac

      - name: Run Ruff
        run: ruff check
        working-directory: ./iac
