name: IAC Up

permissions: write-all

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/iac.up.yaml
      - iac/**

jobs:
  up:
    name: IAC Up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: 'pip'
          cache-dependency-path: iac/requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./iac
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/170633695862/locations/global/workloadIdentityPools/github-action/providers/github-action
          service_account: github-action@makima-dev.iam.gserviceaccount.com
      - name: Refresh Service
        uses: pulumi/actions@v5
        with:
          work-dir: ./iac/service
          command: refresh
          stack-name: DonggeunYu/makima/dev.service
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Preview Service
        uses: pulumi/actions@v5
        with:
          work-dir: ./iac/service
          command: preview
          stack-name: DonggeunYu/makima/dev.service
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Up Service
        uses: pulumi/actions@v5
        with:
          work-dir: ./iac/service
          command: up
          stack-name: DonggeunYu/makima/dev.service
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Refresh Infrastructure
        uses: pulumi/actions@v5
        with:
          work-dir: ./iac/infrastructure
          command: refresh
          stack-name: DonggeunYu/makima/dev.infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Preview Infrastructure
        uses: pulumi/actions@v5
        with:
          work-dir: ./iac/infrastructure
          command: preview
          stack-name: DonggeunYu/makima/dev.infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Up Infrastructure
        uses: pulumi/actions@v5
        with:
          work-dir: ./iac/infrastructure
          command: up
          stack-name: DonggeunYu/makima/dev.infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
